name: Jenkins Environment Variables
description: Converts Buildkite env vars to their Jenkins equivilents 
author: https://github.com/mkmrgn
requirements: []
configuration:
  properties: {}
  additionalProperties: false
